version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/skillit_ai_uk
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - SUPABASE_URL=your-supabase-url
      - SUPABASE_ANON_KEY=your-supabase-anon-key
    depends_on:
      - db
      - redis
    networks:
      - skillit-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skillit_ai_uk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - skillit-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillit-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - skillit-network

volumes:
  postgres_data:
  redis_data:

networks:
  skillit-network:
    driver: bridge
